package LibertyApp;


/**
* LibertyApp/Liberty.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Liberty.idl
* Sunday, August 14, 2016 11:24:34 AM EDT
*/

public interface Liberty extends LibertyOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Liberty
