package LibertyApp;

/**
* LibertyApp/LibertyHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Liberty.idl
* Sunday, August 14, 2016 11:24:34 AM EDT
*/

public final class LibertyHolder implements org.omg.CORBA.portable.Streamable
{
  public LibertyApp.Liberty value = null;

  public LibertyHolder ()
  {
  }

  public LibertyHolder (LibertyApp.Liberty initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = LibertyApp.LibertyHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    LibertyApp.LibertyHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return LibertyApp.LibertyHelper.type ();
  }

}
