package LibertyApp;


/**
* LibertyApp/LibertyOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Liberty.idl
* Sunday, August 14, 2016 11:24:34 AM EDT
*/

public interface LibertyOperations 
{
  String LibertyU ();
} // interface LibertyOperations
