package LibertyApp;


/**
* LibertyApp/LibertyHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Liberty.idl
* Sunday, August 14, 2016 11:24:34 AM EDT
*/

abstract public class LibertyHelper
{
  private static String  _id = "IDL:LibertyApp/Liberty:1.0";

  public static void insert (org.omg.CORBA.Any a, LibertyApp.Liberty that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static LibertyApp.Liberty extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (LibertyApp.LibertyHelper.id (), "Liberty");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static LibertyApp.Liberty read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_LibertyStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, LibertyApp.Liberty value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static LibertyApp.Liberty narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof LibertyApp.Liberty)
      return (LibertyApp.Liberty)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      LibertyApp._LibertyStub stub = new LibertyApp._LibertyStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static LibertyApp.Liberty unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof LibertyApp.Liberty)
      return (LibertyApp.Liberty)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      LibertyApp._LibertyStub stub = new LibertyApp._LibertyStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
