DESCRIBE JOB_GRADES;

SELECT e.LAST_NAME, e.JOB_ID, d.DEPARTMENT_NAME, e.SALARY, j.GRADE_LEVEL
FROM EMPLOYEES e join DEPARTMENTS d on e.DEPARTMENT_ID = d.DEPARTMENT_ID
join JOB_GRADES j on e.SALARY between j.LOWEST_SAL and j.HIGHEST_SAL ;