Select e.last_name, e.JOB_ID, d.DEPARTMENT_ID, d.DEPARTMENT_NAME
FROM EMPLOYEES e 
join DEPARTMENTS d on e.DEPARTMENT_ID = d.DEPARTMENT_ID 
join LOCATIONS l on d.LOCATION_ID = l.LOCATION_ID
WHERE l.CITY = 'Toronto';