SELECT e.LAST_NAME, d.DEPARTMENT_NAME, j.JOB_TITLE, 
Round((CURRENT_DATE -  e.HIRE_DATE)/365)-15 experience, jg.GRADE_LEVEL
FROM EMPLOYEES e join DEPARTMENTS d on e.DEPARTMENT_ID = d.DEPARTMENT_ID
join JOBS j on e.JOB_ID = j.JOB_ID
join JOB_GRADES jg on e.SALARY between jg.LOWEST_SAL and jg.HIGHEST_SAL 
order by d.DEPARTMENT_ID;