SELECT DISTINCT h.HOSPITAL_NAME, count(d.DEPARTMENTID) "number of active departments"
FROM HOSPITALS h join Departments d 
on h.HOSPITALID = d.FK_HOSPITALID
group by h.HOSPITAL_NAME;

SELECT p.PATIENT_FIRST_NAME, p.PATIENT_LAST_NAME, 
s.SUPPLY_NAME, s.SUPPLY_TYPE, 
s.SUPPLY_COST * s.SUPPLY_QUANTIY_USED "cost of itmes used"
FROM PATIENTS p join visits v 
on p.PATIENTID = v.FK_PATIENTID 
join supplies s 
on v.VISITID = s.FK_VISITID ;

SELECT  p.PATIENT_FIRST_NAME, p.PATIENT_LAST_NAME, v.VISIT_COST 
FROM PATIENTS p join visits v on p.PATIENTID = v.FK_PATIENTID 
where v.VISIT_COST > (SELECT AVG(VISIT_COST) FROM visits);

SELECT HOSPITALID, HOSPITAL_NAME, HOSPITAL_CITY, HOSPITAL_COUNTRY, HOSPITAL_PRIMARY_LANGUAGE 
FROM HOSPITALS
where HOSPITALID in(
SELECT HOSPITALID FROM HOSPITALS minus 
(SELECT DISTINCT FK_HOSPITALID FROM Departments));

SELECT * FROM Departments
where DEPARTMENTID in 
(select DEPARTMENTID 
from Departments d join VISITS v 
on d.DEPARTMENTID = v.FK_DEPARTMENTID
where v.VISIT_COST > 0);

SELECT STAFFID, STAFF_FIRST_NAME, STAFF_LAST_NAME, FK_DEPARTMENTID, STAFF_EMAIL FROM Staff
where STAFFID in
(SELECT DISTINCT STAFFID 
FROM Staff s join Departments d 
on s.FK_DEPARTMENTID = d.DEPARTMENTID 
join visits v 
on d.DEPARTMENTID = v.FK_DEPARTMENTID);

SELECT VISITID, VISIT_DISCHARGE_DATE - VISIT_DATE "visist length", 
FK_PATIENTID, FK_DEPARTMENTID, VISIT_COST 
FROM Visits
where VISIT_DISCHARGE_DATE is not null and VISITID IN 
(SELECT VISITID FROM Visits minus 
(SELECT VISITID FROM Visits
where VISIT_COST > (SELECT AVG(VISIT_COST) 
FROM visits)));

CREATE INDEX HOSPITALS_index
ON HOSPITALS (HospitalID, Hospital_Name);

CREATE INDEX Departments_index
ON Departments (DepartmentID, Department_Name);

CREATE INDEX Staff_index
ON Staff (StaffID, Staff_First_Name, Staff_Last_Name);

CREATE INDEX PATIENTS_index
ON PATIENTS (PatientID, Patient_First_Name, Patient_Last_Name);

CREATE INDEX Visits_index
ON Visits (VisitID, Visit_Date);

CREATE INDEX SUPPLIES_index
ON SUPPLIES (SupplyID, Supply_Name);

DROP VIEW Patents_of_Serious_Care;
create view Patents_of_Serious_Care as 
SELECT p.PATIENTID, v.VISIT_DATE, v.VISIT_COST, 
p.PATIENT_FIRST_NAME, p.PATIENT_LAST_NAME, 
p.PATIENT_DOB, p.PATIENT_PHONE, p.PATIENT_EMAIL, 
p.PATIENT_ADDRESS, p.PATIENT_CITY, p.PATIENT_ZIP
FROM PATIENTS p join visits v 
on p.PATIENTID = v.FK_PATIENTID 
join Departments d 
on d.DEPARTMENTID = v.FK_DEPARTMENTID 
join HOSPITALS h 
on d.FK_HOSPITALID = h.HOSPITALID
where HOSPITALID = 1004;

drop view Staff_of_Brave;
create view Staff_of_Brave as 
SELECT s.STAFFID, d.DEPARTMENTID, d.DEPARTMENT_NAME, 
s.STAFF_FIRST_NAME, s.STAFF_LAST_NAME, s.STAFF_PHONE, s.STAFF_EMAIL, 
s.STAFF_OFFICE_LOCATION, s.STAFF_ADDESS, s.STAFF_CITY, s.STAFF_ZIP 
FROM Staff s 
join Departments d 
on s.FK_DEPARTMENTID = d.DEPARTMENTID 
join HOSPITALS h 
on d.FK_HOSPITALID = h.HOSPITALID
where HOSPITALID = 1002;

DROP SEQUENCE PATIENTID_SEQUENCE;
CREATE SEQUENCE PATIENTID_SEQUENCE
START WITH 1010
INCREMENT BY 1
MAXVALUE 9000;