SELECT e.FIRST_NAME, e.LAST_NAME, j.JOB_TITLE, e.SALARY ,j.MIN_SALARY, j.MAX_SALARY,
CASE WHEN e.salary BETWEEN j.MIN_SALARY and j.MAX_SALARY THEN 'yes'
ELSE 'no' END Within_range
FROM EMPLOYEES e join JOBs j on e.JOB_ID = j.JOB_ID
order by e.LAST_NAME;