SELECT EMPLOYEE_ID, LAST_NAME, SALARY, DEPARTMENT_ID
FROM employees
WHERE MANAGER_ID = &Manger_ID
order by &order_collum;

SELECT EMPLOYEE_ID, LAST_NAME, SALARY, DEPARTMENT_ID
FROM employees
WHERE MANAGER_ID = &Manger_ID
order by &order_collum;

SELECT EMPLOYEE_ID, LAST_NAME, SALARY, DEPARTMENT_ID
FROM employees
WHERE MANAGER_ID = &Manger_ID
order by &order_collum;