package invintoryApp;


/**
* invintoryApp/invintory.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from invintory.idl
* Friday, August 26, 2016 7:44:01 PM EDT
*/

public interface invintory extends invintoryOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
   
  
  public String checkAvailability(String item);
  
  
  public short checkStock(String item);
  
  
  public String sellItem (String item);
  
  public String listLowStock ();
  

   public String listItems();
} // interface invintory
