package invintoryApp;


/**
* invintoryApp/invintoryPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from invintory.idl
* Friday, August 26, 2016 7:44:01 PM EDT
*/

public abstract class invintoryPOA extends org.omg.PortableServer.Servant
 implements invintoryApp.invintoryOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static final java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("checkAvailability", new java.lang.Integer (4));
    _methods.put ("checkStock", new java.lang.Integer (3));
    _methods.put ("sellItem", new java.lang.Integer (2));
    _methods.put ("listLowStock", new java.lang.Integer (1));
    _methods.put ("listItems", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 4:  // invintoryApp/invintory/checkAvailability
       {
         String item = in.read_string ();
         String $result = null;
         $result = this.checkAvailability (item);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // invintoryApp/invintory/checkStock
       {
         String item = in.read_string ();
         short $result = (short)0;
         $result = this.checkStock (item);
         out = $rh.createReply();
         out.write_short ($result);
         break;
       }

       case 2:  // invintoryApp/invintory/sellItem
       {
         String item = in.read_string ();
         String $result = null;
         $result = this.sellItem (item);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // invintoryApp/invintory/listLowStock
       {
         String $result = null;
         $result = this.listLowStock ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }
       
       case 0:  // invintoryApp/invintory/listItems
       {
         String $result = null;
         $result = this.listItems ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:invintoryApp/invintory:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public invintory _this() 
  {
    return invintoryHelper.narrow(
    super._this_object());
  }

  public invintory _this(org.omg.CORBA.ORB orb) 
  {
    return invintoryHelper.narrow(
    super._this_object(orb));
  }


} // class invintoryPOA
