package invintoryApp;


/**
* invintoryApp/invintoryHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from invintory.idl
* Friday, August 26, 2016 7:44:01 PM EDT
*/

abstract public class invintoryHelper
{
  private static String  _id = "IDL:invintoryApp/invintory:1.0";

  public static void insert (org.omg.CORBA.Any a, invintoryApp.invintory that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static invintoryApp.invintory extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (invintoryApp.invintoryHelper.id (), "invintory");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static invintoryApp.invintory read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_invintoryStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, invintoryApp.invintory value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static invintoryApp.invintory narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof invintoryApp.invintory)
      return (invintoryApp.invintory)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      invintoryApp._invintoryStub stub = new invintoryApp._invintoryStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static invintoryApp.invintory unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof invintoryApp.invintory)
      return (invintoryApp.invintory)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      invintoryApp._invintoryStub stub = new invintoryApp._invintoryStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
