SELECT EMPLOYEE_ID, LAST_NAME, DEPARTMENT_ID FROM EMPLOYEES 
minus
SELECT EMPLOYEE_ID, LAST_NAME, DEPARTMENT_ID FROM EMPLOYEES
Where DEPARTMENT_ID is not null;

SELECT DEPARTMENT_ID "departments with no employees" FROM DEPARTMENTS
minus(
SELECT DEPARTMENT_ID FROM EMPLOYEES 
INTERSECT
SELECT DEPARTMENT_ID FROM DEPARTMENTS );

SELECT EMPLOYEE_ID, LAST_NAME, TO_DATE(null) "START_DATE", TO_DATE(null) "END_DATE", JOB_ID FROM EMPLOYEES 
UNION
SELECT EMPLOYEE_ID, TO_CHAR(null), START_DATE, END_DATE, JOB_ID FROM JOB_HISTORY
ORDER BY EMPLOYEE_ID, START_DATE DESC;
