SELECT LAST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY > (SELECT min(SALARY) from EMPLOYEES WHERE department_id = 60);

SELECT LAST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY > ANY (SELECT SALARY from EMPLOYEES WHERE department_id = 60);